// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeTXlddHCs4Mg797oyUII8AHIGScBFDx8',
    appId: '1:654950259371:web:e4ba59b0daf31242d4f5ee',
    messagingSenderId: '654950259371',
    projectId: 'fitnesstracker-df73c',
    authDomain: 'fitnesstracker-df73c.firebaseapp.com',
    storageBucket: 'fitnesstracker-df73c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAWOvBsZofMNU9MXhgo4YpPWrEhqUCHI0',
    appId: '1:654950259371:android:d75799a79c52d867d4f5ee',
    messagingSenderId: '654950259371',
    projectId: 'fitnesstracker-df73c',
    storageBucket: 'fitnesstracker-df73c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQjA8fU7JUzUoOQeL71wo33W4ihU297s',
    appId: '1:654950259371:ios:9bb603cdb19e0046d4f5ee',
    messagingSenderId: '654950259371',
    projectId: 'fitnesstracker-df73c',
    storageBucket: 'fitnesstracker-df73c.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeTXlddHCs4Mg797oyUII8AHIGScBFDx8',
    appId: '1:654950259371:web:bdeedfa8511271b4d4f5ee',
    messagingSenderId: '654950259371',
    projectId: 'fitnesstracker-df73c',
    authDomain: 'fitnesstracker-df73c.firebaseapp.com',
    storageBucket: 'fitnesstracker-df73c.firebasestorage.app',
  );
}
